import shutit

s = shutit.create_session(session_type='bash', loglevel='debug', vagrant_memory=4096, vagrant_cpu=2)
s.send('rm -rf /tmp/tf_build && mkdir -p /tmp/tf_build')
s.send('cd /tmp/tf_build')
s.send('git clone https://github.com/hashicorp/terraform.git')
s.send('cd terraform')
s.send('git checkout v0.12-dev')
s.send('vagrant destroy -f || true')
s.send('vagrant up')
s.login(command='vagrant ssh')
s.login('sudo su')
s.send('apt update -y && apt install unzip')
s.send('PROTOC_ZIP=protoc-3.3.0-linux-x86_64.zip')
s.send('curl -OL https://github.com/google/protobuf/releases/download/v3.3.0/$PROTOC_ZIP')
s.send('sudo unzip -o $PROTOC_ZIP -d /usr/local bin/protoc')
s.send('rm -f $PROTOC_ZIP')
s.logout()
s.send('go get -u github.com/golang/protobuf/protoc-gen-go')
s.send('go install github.com/golang/protobuf/protoc-gen-go')
s.send('go get github.com/golang/mock/gomock')
s.send('go install github.com/golang/mock/mockgen')
s.send('cd /opt/gopath/src/github.com/hashicorp/terraform/')
s.send('make fmt')
s.send('make test')
s.send('make bin')
s.pause_point('')
s.logout(command='vagrant ssh')
